---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
script: <%= @configs['script'] %>
rvm:
<% @configs['rvm'].each do |rvm| -%>
  - <%= rvm %>
<% end -%>
env:
<% @configs['env'].each do |env| -%>
  - <%= env %>
<% end -%>

matrix:
  fast_finish: true
  exclude:
<% @configs['exclude'].each do |exc| -%>
    - rvm: <%= exc['rvm'] %>
      env: <%= exc['env'] %>
<% end -%>

notifications:
  email: false
